## YAML Template.
server:
    port: 8001   

spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
      
clicktop:           
    datasource:
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 0
        maximumPoolSize: 50
        validationTimeout: 10000
        idleTimeout: 30000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:
            dataUrl: jdbc:mysql://localhost:3306/clicktop?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Cuiaba&useLegacyDatetimeCode=false         
            dataSourceUser: root
            dataSourcePassword: password
            port: 3306            
            connectionTestQuery: SELECT 1  
 
email:
    host: smtpout.secureserver.net
    port: 465
    username: contato@clicktop.app
    password: Clicktop@2020
    auth: true  
    protocol: smtps
    starttls:
           enable: true
           required: true   

